// Do not edit. This file is machine generated by the Resource DLL Wizard.

library dBASElibrary;

{$R *.RES}
{ITE} {LCID:00000409:00000407} {}
{ITE} {RCFileType} {dBASElibrary_DRC.rc}

{$R 'dBASElibrary_DRC.res' 'dBASElibrary_DRC.rc'}

{$E DEU}

begin
end.